"""
Paste/import patch for the existing HVAC v3 core solver.

Use this when your current solver already produces a daily DataFrame.
It adds v3.1 calibrated baseline columns without rewriting the whole app.

Example inside your current pipeline:

from hvac_v31_core_solver_patch import apply_hvac_v31_patch_to_daily_results

refined_daily = apply_hvac_v31_patch_to_daily_results(
    daily_df,
    calibration_json="outputs/hvac_v31_calibration_coefficients.json"
)

Use refined_daily["energy_kwh_v31_final"] as the calibrated clean baseline.
Then rebuild S0-S3 degradation/strategy scenarios on top of this baseline.
"""

from __future__ import annotations
from pathlib import Path
import pandas as pd

from hvac_v31_engine import BuildingSpec, HVACSpec, CalibrationConfig, compute_v31_baseline


def apply_hvac_v31_patch_to_daily_results(
    daily_df: pd.DataFrame,
    calibration_json: str | Path | None = None,
    building: BuildingSpec | None = None,
    hvac: HVACSpec | None = None,
) -> pd.DataFrame:
    """Apply HVAC v3.1 baseline calculation and optional DB calibration.

    Parameters
    ----------
    daily_df:
        Existing solver output containing weather/driver columns such as T_amb_C,
        T_mean_C, RH_mean_pct, GHI_mean_Wm2, occ, day_of_year.
    calibration_json:
        JSON generated by calibrate_hvac_v31_designbuilder.py. If omitted, only
        uncalibrated v3.1 physics is applied.
    building, hvac:
        Optional dataclasses for custom settings.
    """
    cal = CalibrationConfig.load(calibration_json) if calibration_json else CalibrationConfig.empty()
    v31 = compute_v31_baseline(daily_df, building or BuildingSpec(), hvac or HVACSpec(), cal)

    out = daily_df.copy().reset_index(drop=True)
    columns_to_copy = [
        "Q_env_heat_kwh", "Q_env_cool_kwh", "Q_inf_heat_kwh", "Q_inf_cool_kwh",
        "Q_solar_gain_kwh", "Q_internal_gain_kwh", "Q_cool_load_kwh", "Q_heat_load_kwh",
        "PLR_cool", "PLR_heat", "COP_cool_eff", "cooling_electricity_kwh",
        "heating_energy_kwh", "fan_kwh", "pump_kwh", "auxiliary_kwh",
        "energy_kwh_v31_physics", "monthly_factor", "energy_kwh_v31_seasonal",
        "residual_correction_kwh", "energy_kwh_v31_final", "co2_kg_v31", "cost_usd_v31",
    ]
    for c in columns_to_copy:
        if c in v31.columns:
            out[c] = v31[c].values
    return out
